### ISSUE TITLE
ArgumentError: comparison of Gem::Version with String failed

### ISSUE THREAD

**Issue by cesc1989** [devaspros/puntapie#6]
Error full message:

```
Bundle complete! 31 Gemfile dependencies, 103 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
ArgumentError: comparison of Gem::Version with String failed
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person/loaders/active_model_has_person_name.rb:1:in `<'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person/loaders/active_model_has_person_name.rb:1:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person.rb:5:in `require'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person.rb:5:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/pruebapunta/config/application.rb:19:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/pruebapunta/Rakefile:4:in `require_relative'
/Users/francisco/projects/devaspros-projects/pruebapunta/Rakefile:4:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
ArgumentError: comparison of Gem::Version with String failed
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person/loaders/active_model_has_person_name.rb:1:in `<'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person/loaders/active_model_has_person_name.rb:1:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person.rb:5:in `require'
/Users/francisco/.gem/ruby/3.1.0/gems/name_of_person-1.1.2/lib/name_of_person.rb:5:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/pruebapunta/config/application.rb:19:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/pruebapunta/Rakefile:4:in `require_relative'
/Users/francisco/projects/devaspros-projects/pruebapunta/Rakefile:4:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'

```

**Comment by cesc1989** [comment]
Fixed by removing gem `gem 'name_of_person', '~> 1.1'`
