### ISSUE TITLE
rails aborted! Unknown version "7.1" - when generating app from template

### ISSUE THREAD

**Issue by cesc1989** [devaspros/puntapie#9]
Error log:

```
       rails  importmap:install
rails aborted!
Unknown version "7.1"
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/application/configuration.rb:261:in `load_defaults'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:24:in `<class:Application>'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:23:in `<module:Puntaprueba>'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:21:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/puntaprueba/Rakefile:4:in `require_relative'
/Users/francisco/projects/devaspros-projects/puntaprueba/Rakefile:4:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
Unknown version "7.1"
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/application/configuration.rb:261:in `load_defaults'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:24:in `<class:Application>'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:23:in `<module:Puntaprueba>'
/Users/francisco/projects/devaspros-projects/puntaprueba/config/application.rb:21:in `<top (required)>'
/Users/francisco/projects/devaspros-projects/puntaprueba/Rakefile:4:in `require_relative'
/Users/francisco/projects/devaspros-projects/puntaprueba/Rakefile:4:in `<top (required)>'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
/Users/francisco/.gem/ruby/3.1.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by cesc1989** [comment]
I'm using Ruby 3.1.0
```
$ chruby
   ruby-2.7.7
   ruby-3.0.2
   ruby-3.0.4
   ruby-3.0.6
 * ruby-3.1.0
```

And it's using Rails 7.1.0 ???

```
$ rails --version
Rails 7.1.3

$ which rails
/Users/francisco/.gem/ruby/3.1.0/bin/rails
```

**Comment by cesc1989** [comment]
The error is because the rails new command is using rails 7.1.0 (don't know why is picking up that version.

To run it it an specific version:
```
rails _7.0.1_ new ./pietest -d sqlite3 -m puntapie/template.rb
```
